before_install: sudo apt-get install python3-pyparsing
install:
- git clone https://github.com/combatopera/aridity.git ../aridity
- git clone https://github.com/combatopera/pyven.git ../pyven
script: ./travis_ci.sh
sudo: required
dist: trusty
language: generic
